<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class CarModelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Brands and models to be associated
        $brands = [
            'Acura' => [
                'Integra',
                'TLX',
                'MDX',
                'RDX',
                'NSX',
                'ZDX',
                'ILX',
                'RLX',
                'Legend',
            ],
            'Alfa Romeo' => [
                'Giulia',
                'Stelvio',
                'Tonale',
                '4C',
                'Spider',
                '164',
                'GTV',
                'Milano',
                'Brera',
                '8C Competizione',
            ],
            'Aston Martin' => [
                'DB11',
                'DBX',
                'Vantage',
                'Rapide',
                'Vanquish',
                'Valhalla',
                'Valkyrie',
                'Lagonda',
            ],
            'Audi' => [
                'A3',
                'A4',
                'A5',
                'A6',
                'A7',
                'A8',
                'Q2',
                'Q3',
                'Q5',
                'Q7',
                'Q8',
                'e-tron',
                'TT',
                'R8',
            ],
            'Bentley' => [
                'Continental GT',
                'Flying Spur',
                'Bentayga',
                'Mulsanne',
                'Arnage',
                'Azure',
                'Brooklands',
                'Turbo R',
            ],
            'BMW' => [
                'X1',
                'X3',
                'X5',
                'X6',
                'X7',
                '320i',
                '330i',
                '520i',
                '530i',
                'M3',
                'M5',
                'i3',
                'i8'
            ],
            'Bugatti' => [
                'Chiron',
                'Veyron',
                'Divo',
                'Bolide',
                'Centodieci',
                'EB110',
                'La Voiture Noire',
                'Type 35',
            ],
            'Buick' => [
                'Encore',
                'Enclave',
                'Envision',
                'LaCrosse',
                'Regal',
                'Verano',
                'Century',
                'Riviera',
                'LeSabre',
                'Roadmaster',
            ],
            'BYD' => [
                'T3',
                'F0',
                'F3',
                'F5',
                'Tang',
                'Song',
                'Qin',
                'Yuan',
                'E5',
                'Dolphin',
                'Han',
                'Atto 3',
                'Seal',
            ],
            'Cadillac' => [
                'Escalade',
                'XT5',
                'XT4',
                'CT4',
                'CT5',
                'Lyriq',
                'ATS',
                'CTS',
                'SRX',
                'DeVille',
                'Eldorado',
            ],
            'Chevrolet' => [
                'Onix',
                'Sonic',
                'Cruze',
                'Tracker',
                'Trailblazer',
                'Spin',
                'Montana',
                'Aveo',
                'Cobalt',
                'Prisma',
                'Spin',
                'Cruz',
                'Camaro',
                'Chevette'
             ],
             'Chery' => [
                'T3',
                'F0',
                'F3',
                'F5',
                'Tang',
                'Song',
                'Qin',
                'Yuan',
                'E5',
                'Dolphin',
                'Han',
                'Atto 3',
                'Seal',
            ],
            'Citroën' => [
                'C3',
                'C4',
                'C5',
                'C3 Aircross',
                'C4 Cactus',
                'Berlingo',
                'DS3',
                'DS4',
                'DS7 Crossback',
                'Aircross'
            ],
            'Dodge' => [
                'Charger',
                'Challenger',
                'Durango',
                'Ram',
                'Journey',
                'Grand Caravan',
                'Viper',
                'Dart',
                'Neon',
                'Avenger',
            ],
            'Ferrari' => [
                '488 GTB', 
                'Portofino', 
                'F8 Tributo', 
                'Roma', 
                'LaFerrari', 
                'GTC4Lusso', 
                '458 Italia'
            ],
            'Fiat' => [ 
                'Palio',
                'Uno',
                'Mobi',
                'Argo',
                'Cronos',
                'Toro',
                'Fiorino',
                'Strada',
                'Freemont',
                'Punto',
                'Doblo',
                '500',
                'Linea',
                'Panda',
                'Fiat 500'
             ],
            'Ford' => [
                'Fiesta',
                'Ka',
                'Focus',
                'Fusion',
                'EcoSport',
                'Ranger',
                'Mustang',
                'Edge',
                'Mondeo',
                'Explorer',
                'Taurus',
                'Puma',
                'Bronco'
            ],
            'Geely' => [
                'Coolray',
                'Azkarra',
                'Emgrand GT',
                'Emgrand EC7',
                'Binrui',
                'Bo Yue',
                'Xingyue L',
                'Preface',
                'Vision',
                'Haoyue',
            ],
            'Genesis' => [
                'G70',
                'G80',
                'G90',
                'GV60',
                'GV70',
                'GV80',
                'Essentia',
                'X Concept',
            ],
            'GMC' => [
                'Sierra',
                'Canyon',
                'Yukon',
                'Terrain',
                'Acadia',
                'Hummer EV',
                'Envoy',
                'Savana',
            ],
            'Honda' => [
                'Civic',
                'HR-V',
                'Fit',
                'Cr-V',
                'City',
                'Pilot',
                'Ridgeline',
                'Accord',
                'Jazz',
                'Insight',
                'Element'
            ],
            'Hyundai' => [
                'HB20',
                'Creta',
                'Elantra',
                'Tucson',
                'Santa Fe',
                'i30',
                'Kona',
                'Veracruz',
                'Sonata',
                'ix35'
            ],
            'Infiniti' => [
                'Q50',
                'QX60',
                'QX80',
                'QX55',
                'Q60',
                'QX50',
                'Q70',
                'EX35',
                'FX35',
            ],
            'Jaguar' => [
                'XF',
                'XJ',
                'F-Type',
                'E-Pace',
                'F-Pace',
                'I-Pace',
                'XE',
                'S-Type',
                'XK',
            ],
            'Jeep' => [
                'Compass',
                'Renegade',
                'Cherokee',
                'Grand Cherokee',
                'Wrangler',
                'Gladiator',
                'Commander'
            ],
            'Kia' => [
                'Picanto', 
                'Seltos', 
                'Sportage', 
                'K5', 
                'Cerato', 
                'Stinger', 
                'Rio', 
                'Carnival'
            ],
            'Lamborghini' => [
                'Aventador',
                'Huracán',
                'Urus',
                'Gallardo',
                'Murciélago',
                'Diablo',
                'Countach',
                'Sian',
                'Reventón',
                'Veneno',
                'Miura',
                'Espada',
            ],
            'Land Rover' => [
                'Range Rover', 
                'Discovery', 
                'Discovery Sport', 
                'Defender', 
                'Evoque', 
                'Velar'
            ],
            'Lexus' => [
                'RX',
                'NX',
                'UX',
                'GX',
                'LX',
                'ES',
                'IS',
                'LS',
                'RC',
                'LC',
                'CT',
                'HS',
            ],
            'Lincoln' => [
                'Navigator',
                'Aviator',
                'Corsair',
                'Nautilus',
                'MKZ',
                'Continental',
                'MKC',
                'MKT',
                'Mark LT',
                'Town Car',
            ],
            'Maserati' => [
                'Ghibli',
                'Levante',
                'Quattroporte',
                'GranTurismo',
                'GranCabrio',
                'MC20',
                'Shamal',
                'Biturbo',
                '3200 GT',
                'Spyder',
            ],
            'Mazda' => [
                'Mazda 3', 
                'Mazda 6', 
                'Mazda CX-5', 
                'Mazda CX-9', 
                'Mazda MX-5 Miata'
            ],
            'McLaren' => [
                '720S',
                '765LT',
                'Artura',
                'P1',
                'Senna',
                'Elva',
                '570S',
                '600LT',
                '650S',
                'MP4-12C',
                'F1',
            ],
            'Mercedes-Benz' => [
                'Classe A',
                'Classe B',
                'Classe C',
                'Classe E',
                'Classe S',
                'GLA',
                'GLC',
                'GLE',
                'GLS',
                'AMG GT',
                'V-Class'
            ],
            'Mini' => [
                'Cooper',
                'Cooper S',
                'Clubman',
                'Countryman',
                'Paceman',
                'Convertible',
                'John Cooper Works',
                'Electric',
                'Hardtop 2 Door',
                'Hardtop 4 Door',
            ],
            'Mitsubishi' => [
                'Outlander', 
                'L200 Triton', 
                'ASX', 
                'Pajero Sport', 
                'Galant', 
                'Eclipse Cross', 
                'Montero'
            ],
            'Nissan' => [
                'Kicks',
                'March',
                'Versa',
                'Sentra',
                'Altima',
                'X-Trail',
                'Frontier',
                '370Z',
                'Leaf',
                'Pathfinder'
            ],
            'Pagani' => [
                'Zonda',
                'Huayra',
                'Huayra Roadster',
                'Zonda R',
                'Zonda Cinque',
                'Zonda F',
                'Zonda HP Barchetta',
                'Zonda Revolución',
                'Zonda Tricolore',
            ],
            'Peugeot' => [
                '208',
                '2008',
                '3008',
                '5008',
                '308',
                '5008',
                'Partner',
                'Expert',
                'Boxer',
                '508'
            ],
            'Porsche' => [
                '911', 
                'Cayenne', 
                'Macan', 
                'Panamera', 
                'Taycan'
            ],
            'Renault' => [
                'Sandero',
                'Logan',
                'Kwid',
                'Captur',
                'Duster',
                'Oroch',
                'Clio',
                'Fluence',
                'Mégane',
                'Koleos'
            ],
            'Rolls-Royce' => [
                'Phantom',
                'Ghost',
                'Wraith',
                'Dawn',
                'Cullinan',
                'Silver Shadow',
                'Silver Spirit',
                'Corniche',
                'Silver Cloud',
            ],
            'Saab' => [
                '9-3',
                '9-5',
                '9-7X',
                '900',
                '9000',
                '99',
                '96',
                'Sonett',
                '92',
                '9-4X',
            ],
            'Subaru' => [
                'Impreza',
                'Outback',
                'Forester',
                'Crosstrek',
                'Ascent',
                'Legacy',
                'BRZ',
                'WRX',
                'Baja',
                'SVX',
            ],
            'Suzuki' => [
                'Vitara', 
                'S-Cross', 
                'Swift', 
                'Jimny', 
                'Baleno', 
                'Grand Vitara', 
                'Celerio'
            ],
            'Tesla' => [
                'Model S',
                'Model 3',
                'Model X',
                'Model Y',
                'Cybertruck',
                'Roadster',
                'Semi',
            ],
            'Toyota' => [
                'Corolla',
                'Hilux',
                'Etios',
                'Yaris',
                'Camry',
                'Fortuner',
                'SW4',
                'Land Cruiser',
                'RAV4',
                'Prado',
                'Avalon',
                'Hilux SW4'
            ],
            'Troller' => [
                'T4',
                'Pantanal',
            ],
            'Volkswagen' => [ 
                'Gol',
                'Polo',
                'Virtus',
                'Jetta',
                'Tiguan',
                'Up!',
                'Fox',
                'Nivus',
                'Passat',
                'Amarok',
                'Golf',
                'Touran',
                'CrossFox',
                'Saveiro',
                'Scirocco',
                'Voyage',
                'Fusca',
                'Beetle',
                'Arteon' 
            ],
            'Volvo' => [
                'XC60', 
                'XC90', 
                'V60', 
                'S60', 
                'S90', 
                'V90', 
                'XC40', 
                'C40 Recharge'
            ],
        ];

        // Loop to insert the models for each brand
        foreach ($brands as $brand => $models) {
            // Searching for the brand by alias
            $brand = DB::table('car_brands')->where('alias', Str::slug($brand))->first();

            if ($brand) {
                foreach ($models as $model) {
                    DB::table('car_models')->insert([
                        'car_brand_id' => $brand->id,
                        'name' => $model,
                        'alias' => Str::slug($model),
                        'active' => true,
                    ]);
                }
            }
        }
    }
}
